# Generated by Django 4.0.1 on 2022-02-24 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('coordinateX', models.FloatField()),
                ('coordinateY', models.FloatField()),
                ('validFrom', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=20)),
                ('value', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.stations')),
            ],
        ),
    ]
