name: DjangoCI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_NAME: meteo
      DB_USER: postgres
      DB_SECRET: ${{ secrets.DB_PASS }}
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: meteo
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd projectXback
        pip install -r requirements.txt    
    - name: Migrations
      run: |
        cd projectXback
        python manage.py migrate
    - name: Run Tests
      run: |
        cd projectXback
        python manage.py test --verbosity=2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
#        projectBaseDir: projectXback
        args: >
          -Dsonar.organization=alexeyosavchenko
          -Dsonar.projectKey=AlexeyOSavchenko_projectX
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./projectXback/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/meteorepo:latest
