name: DjangoCI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: meteo
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 60s
          --health-timeout 5s
          --health-retries 3
      
    steps:
    - uses: actions/checkout@v3
#     - name: Set up Python 3.9
#       uses: actions/setup-python@v3
#       with:
#         python-version: 3.9
#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         cd projectXback
#         pip install -r requirements.txt    
#     - name: Migrations
#       run: |
#         cd projectXback
#         python manage.py migrate
#     - name: Run Tests
#       run: |
#         cd projectXback
#         python manage.py test --verbosity=2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: projectXback
        args: >
          -Dsonar.organization="Alexey Savchenko"
          -Dsonar.projectKey=my-projectX
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
